version: "3"
services:

  backend:
    build: ./backend/src/
    ports:
      - 5000:5000
    command: python3 app.py -p
    environment:
      - ENV=production

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - 80:80
    links:
      - backend
