version: "3"
services:

  backend:
    image: ${BACKEND_REPO}
    build: ./backend/src/
    expose:
      - 3031
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - ENV=production

  frontend:
    image: ${FRONTEND_REPO}
    build: ./frontend/
    depends_on:
      - backend
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    links:
      - backend
